#! /bin/bash

sudo rm -r /var/www/html/upload/
sudo mkdir /var/www/html/upload/
sudo cp lib/* /var/www/html/upload/
sudo chown -R www-data:www-data /var/www/html/upload

sudo gzip /etc/php/7.4/apache2/php.ini
sudo cp lib/conf/php-EDITED.ini /etc/php/7.4/apache2/php.ini
sudo /etc/init.d/apache2 restart
