#!/bin/bash
# user must be root.
if [ "$(id -u)" != "0" ]
then
	echo "This script must be run as root (sudo)." 1>&2
	exit 1
fi
# gets required packages from apt
sudo apt-get update
sudo apt-get install -y php
sudo apt-get install -y apache2
sudo apt-get install -y libapache2-mod-php
# configures /var/www/html
sudo gzip /var/www/html/index.html
sudo chown -R www-data:www-data /var/www/html
