#!/bin/bash
# user must be root.
if [ "$(id -u)" != "0" ]
then
	echo "This script must be run as root (sudo)." 1>&2
	exit 1
fi
# synchronize
sudo rm -rf /var/www/html/"$1" 2>/dev/null
sudo cp -rf "$1" /var/www/html/ 2>/dev/null
sudo chown -R www-data:www-data /var/www/html 2>/dev/null
